version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      test-tooling:
        patterns:
          - "xunit*"
          - "Microsoft.NET.Test.Sdk"
          - "coverlet.*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
