name: .NET 5.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semver:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install git-mkver
        run: curl -L https://github.com/idc101/git-mkver/releases/download/v1.2.2/git-mkver-linux-amd64-1.2.2.tar.gz | tar xvz && mv git-mkver /usr/local/bin
      - name: List all Git Tags
        run: git tag
      - name: determine next version 
        run: git-mkver next
        
  build-and-test:
    needs: [ semver ]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -f net5.0 --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
