name: .NET 5.0 / 6.0

on:
  pull_request:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    # Setup of multiple .NET versions at the same time seams to be broken
    #
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: .NET info
      run: dotnet --info
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -f net5.0 --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
