name: .NET 5.0

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER_EMAIL: ${{ secrets.OWNER_EMAIL }}
      OWNER_NAME: ${{ secrets.OWNER_NAME }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: install git-mkver
      run: curl -L https://github.com/idc101/git-mkver/releases/download/v1.2.2/git-mkver-linux-amd64-1.2.2.tar.gz | tar xvz && mv git-mkver /usr/local/bin
    - name: determine next version
      run: git-mkver next
    - name: patch new version
      run: git-mkver patch
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -f net5.0 --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
 #   - name: setup gpg
 #     run: |
 #       echo "$OWNER_GPG_KEY_BASE64" | base64 -d -i >> signkey.asc
 #       shasum signkey.asc
 #   - name: setup git config
 #     run: |
 #       git config --global user.email "$OWNER_EMAIL"
 #       git config --global user.name "$OWNER_NAME"
 #   - name: add semver tag for new version via git-mkver
 #     run: git-mkver tag
 #   - name: push changes (Tags) to Repository
 #     run: git push origin --tags
